sudo: required
services:
  - docker   # installs docker 
before_install:
  - docker build -f Dockerfile.dev -t manisha\docker-react .
script:
  - docker run manisha\docker-react npm run test -- --coverage